/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/UI/button/Button.vue')['default']
    DropdownMenu: typeof import('./src/components/UI/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./src/components/UI/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./src/components/UI/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./src/components/UI/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./src/components/UI/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./src/components/UI/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./src/components/UI/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./src/components/UI/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./src/components/UI/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./src/components/UI/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./src/components/UI/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./src/components/UI/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./src/components/UI/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./src/components/UI/dropdown-menu/DropdownMenuTrigger.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    IconFlagUSA: typeof import('./src/components/icons/IconFlagUSA.vue')['default']
    IconMagnifyingGlass: typeof import('./src/components/icons/IconMagnifyingGlass.vue')['default']
    IconPerson: typeof import('./src/components/icons/IconPerson.vue')['default']
    IconShoppingCart: typeof import('./src/components/icons/IconShoppingCart.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBlogs: typeof import('./src/components/page/section/SectionBlogs.vue')['default']
    SectionBuyers: typeof import('./src/components/page/section/SectionBuyers.vue')['default']
    SectionCarousel: typeof import('./src/components/page/section/SectionCarousel.vue')['default']
    SectionCategory: typeof import('./src/components/page/section/SectionCategory.vue')['default']
    SectionDeals: typeof import('./src/components/page/section/SectionDeals.vue')['default']
    SectionFeatures: typeof import('./src/components/page/section/SectionFeatures.vue')['default']
    SectionHero: typeof import('./src/components/page/section/SectionHero.vue')['default']
    SectionMission: typeof import('./src/components/page/section/SectionMission.vue')['default']
    SectionReviews: typeof import('./src/components/page/section/SectionReviews.vue')['default']
    UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
  }
}
